variables:
  PACKAGE_NAME: "node-red-contrib-openhab2"

stages:
- build

build_feature_branches:
  stage: build
  image: registry.bongers.co:5005/dev-ops/command-line-builder:latest
  except: [develop, master]
  script:
    - git config --global user.name "GitLab runner"
    - git config --global user.email "gitlab-runner@geertbongers.nl"
    - git checkout develop
    - git pull
    - git merge origin/$CI_COMMIT_REF_NAME
    - mkdir -p /rpool/docker/node-red-data/nodes/$PACKAGE_NAME
    - chown 1001:1001 /rpool/docker/node-red-data/nodes
    - rsync -r --exclude=".*" --exclude "reference" "$PWD/" /rpool/docker/node-red-data/nodes/$PACKAGE_NAME/
    - chown -R 1001:1001 /rpool/docker/node-red-data/nodes/$PACKAGE_NAME
    - docker stop node-red

build_job:
  stage: build
  image: registry.bongers.co:5005/dev-ops/command-line-builder:latest
  only: [develop, master]
  script:
    - mkdir -p /rpool/docker/node-red-data/nodes/$PACKAGE_NAME
    - chown 1001:1001 /rpool/docker/node-red-data/nodes
    - rsync -r --exclude=".*" --exclude "reference" "$PWD/" /rpool/docker/node-red-data/nodes/$PACKAGE_NAME/
    - chown -R 1001:1001 /rpool/docker/node-red-data/nodes/$PACKAGE_NAME
    - docker stop node-red